LEAK_NODE = "leak_node"
DEFAULT_SYMPTOM_LEAK_PROPORTION = 0.1
DEFAULT_MAX_SYMPTOM_PRIOR = 0.9
DEFAULT_MAX_DISEASE_PRIOR = 0.9

DEFAULT_APPLY_CONCEPT_GROUPS = False
DEFAULT_SINGLE_DISEASE_QUERY = True
DEFAULT_IGNORE_OTHER_DISEASES = True
DEFAULT_DOSI_MODE = "prior_adjustment"
DEFAULT_INFERENCE_ALGORITHM = "renormalise"
